[
    {
        stt: 1,
        name: 'Thầy Toàn Cờ Vua',
        dv: 'Quân Đội',
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
    {
        stt: 2,
        name: 'Lê Trọng Đề Toàn',
        dv: 'Thanh Hóa',
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
    {
        stt: 3,
        name: 'Lê Minh Khôi',
        dv: 'Hà Nội',
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
    {
        stt: 4,
        name: 'Phùng Thị Tuyết Lan',
        dv: 'Hồ Chí Minh',
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
    {
        stt: 5,
        name: 'Lê Quang Liêm',
        dv: 'HCM',
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
    {
        stt: 6,
        name: 'Lê Tuấn Minh',
        dv: 'Hà Nội',
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
    {
        stt: 7,
        name: 'Chim Sẻ Đi Nắng',
        dv: 'Hà Nội',
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
    {
        name: 'Miễn Đấu',
        dv: '',
        stt: 8,
        listScore: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        myScore: 0,
        hsdk: 0,
        hsbg: 0,
        hsw: 0,
        hstb: 0,
        hsb: 0,
    },
];

//   lưu dữ liệu có cấu trúc sau vào mongoose
