[
    [1, 8, 'HCM 4', 'HCM', '6'],
    [2, 1, 'Hà Nội 1', 'Hà Nội', '5'],
    [3, 12, 'QDO 4', 'QDO', '4½'],
    [4, 7, 'HCM 3', 'HCM', '4'],
    [5, 6, 'HCM 2', 'HCM', '4'],
    [6, 16, 'Thanh Hóa 1', 'THO', '4'],
    [7, 10, 'QDO 2', 'QDO', '4'],
    [8, 2, 'Hà Nội 2', 'Hà Nội', '3½'],
    [9, 4, 'Hà Nội 4', 'Hà Nội', '3½'],
    [10, 3, 'Hà Nội 3', 'Hà Nội', '3½'],
    [11, 15, 'Thanh Hóa 1', 'THO', '3'],
    [12, 13, 'Thanh Hóa 1', 'THO', '3'],
    [13, 9, 'QDO 1', 'QDO', '2½'],
    [14, 5, 'HCM 1', 'HCM', '2½'],
    [15, 14, 'Thanh Hóa 1', 'THO', '2'],
    [16, 11, 'QDO 3', 'QDO', '1'],
];

[
    { stt: 1, hang: 8, name: 'HCM 4', clb: 'HCM', score: 6 },
    { stt: 2, hang: 1, name: 'Hà Nội 1', clb: 'Hà Nội', score: 5 },
    { stt: 3, hang: 12, name: 'QDO 4', clb: 'QDO', score: 4.5 },
    { stt: 4, hang: 7, name: 'HCM 3', clb: 'HCM', score: 4 },
    { stt: 5, hang: 6, name: 'HCM 2', clb: 'HCM', score: 4 },
    { stt: 6, hang: 16, name: 'Thanh Hóa 1', clb: 'THO', score: 4 },
    { stt: 7, hang: 10, name: 'QDO 2', clb: 'QDO', score: 4 },
    { stt: 8, hang: 2, name: 'Hà Nội 2', clb: 'Hà Nội', score: 3.5 },
    { stt: 9, hang: 4, name: 'Hà Nội 4', clb: 'Hà Nội', score: 3.5 },
    { stt: 10, hang: 3, name: 'Hà Nội 3', clb: 'Hà Nội', score: 3.5 },
    { stt: 11, hang: 15, name: 'Thanh Hóa 1', clb: 'THO', score: 3 },
    { stt: 12, hang: 13, name: 'Thanh Hóa 1', clb: 'THO', score: 3 },
    { stt: 13, hang: 9, name: 'QDO 1', clb: 'QDO', score: 2.5 },
    { stt: 14, hang: 5, name: 'HCM 1', clb: 'HCM', score: 2.5 },
    { stt: 15, hang: 14, name: 'Thanh Hóa 1', clb: 'THO', score: 2 },
    { stt: 16, hang: 11, name: 'QDO 3', clb: 'QDO', score: 1 },
];
